version: "3.9"
services:
  opensearch:
    image: opensearchproject/opensearch:1.0.0
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - discovery.type=single-node

  example_flaskapp:
    build: .
    volumes:
      ["./src:/app", "./data:/data"]
    ports:
      - 5000:5000
    environment:
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_USER=admin
      - OPENSEARCH_PASSWORD=admin
      - OPENSEARCH_PORT=9200
      - PYTHONPATH=/app
      - LOG_LEVEL=debug